# Generated by Django 4.2.2 on 2023-07-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=130)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('senha', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Vaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('raca', models.CharField(max_length=150)),
                ('idade', models.IntegerField(max_length=8)),
                ('kg', models.IntegerField(max_length=8)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leite.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Rendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dia', models.DateField()),
                ('vaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leite.vaca')),
            ],
        ),
    ]
