# Generated by Django 4.2.2 on 2023-07-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leite', '0002_alter_vaca_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaca',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vaca',
            name='kg',
            field=models.FloatField(),
        ),
    ]
