# Generated by Django 4.2.2 on 2023-07-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leite', '0003_alter_vaca_idade_alter_vaca_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimento',
            name='dia',
            field=models.CharField(max_length=8),
        ),
    ]
